#!/bin/sh
#
# Autostart file

# play startup chime
#mpv --no-config --no-terminal "$XDG_DATA_HOME"/sounds/chicago95-startup.ogg &

# set wallpaper
wallset

# remap capslock and escape
setxkbmap -option "caps:escape"
setxkbmap -option "shift:both_capslock"

# source Xresources
xrdb "$XDG_CONFIG_HOME"/Xresources

# enable numlock
numlockx

# openbox window snap
opensnap &

# compositor
picom &

# Notification daemon
/usr/lib/xfce4/notifyd/xfce4-notifyd &

# panel
xfce4-panel &

# desktop icons
nemo-desktop &

# network manager applet
nm-applet &

# battery icon
cbatticon -n -i notification -l 25 -r 15 &

# polkit authentication agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# usb automount
udiskie -sn &

# start qbittorrent
sleep 10 && qbittorrent &

# redshift
sleep 10 && redshift-gtk -l 31.6:74.3 &
